---
keys:
  - &xekuri age19c86cszvjkvlrax8y5dqzu79q8d98z64tkdkcy8keyu3lu0ezveswn8yve
  - &grovebringer age1ya6qk3spwk2prnjcd6c9jfkt4607cvengxt46lu4pvuedzefygrsvjdydg
  - &aureliteiron age1ya6qk3spwk2prnjcd6c9jfkt4607cvengxt46lu4pvuedzefygrsvjdydg

creation_rules:
  - path_regex: secrets/grovebringer/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *xekuri
          - *grovebringer
  - path_regex: secrets/xekuri/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *xekuri
  - path_regex: secrets/aureliteiron/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *xekuri
          - *aureliteiron
