---
keys:
  - &75cherries age1s9qwejl2km8xjrcw47mndevfhv720pnrzd4a5d7j35rqk0mv65zq624j62
  - &cherries age1s9qwejl2km8xjrcw47mndevfhv720pnrzd4a5d7j35rqk0mv65zq624j62
creation_rules:
  - path_regex: secrets/75cherries/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *75cherries
          - *cherries
  - path_regex: secrets/cherries/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *cherries
          - *75cherries
