# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd = {
      availableKernelModules = [
        "xhci_pci"
        "vmd"
        "ahci"
        "nvme"
        "usb_storage"
        "sd_mod"
      ];
      kernelModules = [
      ];
    };
    kernelModules = [
      "kvm-intel"
    ];
    extraModulePackages = [
    ];
    initrd.luks.devices."luks-ebb3f200-58ce-4881-aa06-b1902cf4e768".device = "/dev/disk/by-uuid/ebb3f200-58ce-4881-aa06-b1902cf4e768";
  };

  fileSystems = {
    "/" = {
      device = "/dev/mapper/luks-ebb3f200-58ce-4881-aa06-b1902cf4e768";
      fsType = "btrfs";
      options = [
        "subvol=@"
      ];
    };
    "/home" = {
      device = "/dev/mapper/luks-ebb3f200-58ce-4881-aa06-b1902cf4e768";
      fsType = "btrfs";
      options = [
        "subvol=@home"
      ];
    };
    "/boot" = {
      device = "/dev/disk/by-uuid/D763-93A3";
      fsType = "vfat";
      options = [
        "fmask=0077"
        "dmask=0077"
      ];
    };
  };

  swapDevices = [
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
